export type ServerAsset = { id: string; ownerUserId: string; ownerName: string; departmentId: string | null; departmentName: string | null; projectId: string | null; projectName: string | null; taskId: string | null; filename: string; mimeType: string; byteSize: number; kind: "image" | "video" | "text" | "other"; source: string; operationType: string | null; prompt: string | null; modelName: string | null; status: string; metadata: Record<string, unknown>; createdAt: string };
export type ServerProject={id:string;externalId:string;name:string;ownerName:string;departmentName:string|null;status:string;taskCount:number;assetCount:number;credits:number;updatedAt:string};

async function request<T>(path: string, init?: RequestInit): Promise<T> { const response=await fetch(path,{...init,credentials:"include"}); if(!response.ok){const payload=await response.json().catch(()=>({})) as {message?:string};throw new Error(payload.message||"素材请求失败");} return response.status===204?undefined as T:response.json() as Promise<T>; }
export const listServerAssets=()=>request<{assets:ServerAsset[]}>("/api/assets");
export const listAdminServerAssets=()=>request<{assets:ServerAsset[]}>("/api/admin/assets");
export const listAdminServerProjects=()=>request<{projects:ServerProject[]}>("/api/admin/projects");
export async function uploadServerAsset(file:File, metadata:Record<string,unknown>={}) { const created=await request<{assetId:string;uploadUrl:string}>("/api/assets/upload-request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filename:file.name,mimeType:file.type||"application/octet-stream",byteSize:file.size,kind:file.type.startsWith("image/")?"image":file.type.startsWith("video/")?"video":file.type.startsWith("text/")?"text":"other",metadata})}); await request<void>(created.uploadUrl,{method:"PUT",headers:{"content-type":file.type||"application/octet-stream"},body:file}); return created.assetId; }
export const deleteServerAsset=(id:string)=>request<void>(`/api/assets/${id}`,{method:"DELETE"});
