import { Router } from "express";
import { z } from "zod";
import type { AppConfig } from "../config";
import type { Database } from "../db";
import { decryptSecret } from "../security";
import type { AuthenticatedRequest } from "../types";
import { writeAudit } from "../audit";
import { assertModuleEnabled } from "../module-flags";

const schema=z.object({modelId:z.string().min(1).max(200),input:z.array(z.unknown()).max(200),tools:z.array(z.unknown()).max(100).default([]),toolChoice:z.unknown().optional()});
export function createChatRouter(db:Database,config:AppConfig){const router=Router();router.post("/responses",async(request,response,next)=>{try{const input=schema.parse(request.body);await assertModuleEnabled(db,"gpt-chat");const actor=(request as unknown as AuthenticatedRequest).auth;const result=await db.query<{model_id:string;base_url:string;protocol:string;encrypted_credentials:string|null}>(`SELECT m.model_id,p.base_url,p.protocol,p.encrypted_credentials FROM model_configs m JOIN providers p ON p.id=m.provider_id WHERE (m.id::text=$1 OR m.model_id=$1) AND m.enabled=true AND p.enabled=true AND 'chat'=ANY(m.capabilities) LIMIT 1`,[input.modelId]);const model=result.rows[0];if(!model){response.status(400).json({error:"MODEL_DISABLED",message:"管理员尚未启用该对话模型"});return;}if(!model.encrypted_credentials||!config.PROVIDER_ENCRYPTION_KEY){response.status(503).json({error:"PROVIDER_NOT_CONFIGURED",message:"对话模型服务端凭据未配置"});return;}if(model.protocol!=="openai"&&model.protocol!=="custom"){response.status(400).json({error:"PROTOCOL_NOT_SUPPORTED",message:"当前对话入口暂不支持该 Provider 协议"});return;}const credentials=JSON.parse(decryptSecret(model.encrypted_credentials,config.PROVIDER_ENCRYPTION_KEY)) as Record<string,string>;const upstream=await fetch(`${model.base_url.replace(/\/$/,"")}/responses`,{method:"POST",headers:{"content-type":"application/json",...(credentials.apiKey?{authorization:`Bearer ${credentials.apiKey}`}:{})},body:JSON.stringify({model:model.model_id,input:input.input,tools:input.tools,tool_choice:input.toolChoice??"auto",parallel_tool_calls:false}),signal:AbortSignal.timeout(180000)});if(!upstream.ok)throw new Error(`对话 Provider ${upstream.status}: ${(await upstream.text()).slice(0,500)}`);const body=await upstream.json() as {output_text?:string;output?:Array<{type?:string;content?:Array<{text?:string}>;id?:string;call_id?:string;name?:string;arguments?:string;thoughtSignature?:string}>};const content=body.output_text||body.output?.flatMap((item)=>item.type==="message"?item.content||[]:[]).map((item)=>item.text||"").join("")||"";const toolCalls=(body.output||[]).filter((item)=>item.type==="function_call"&&item.name).map((item)=>({id:item.call_id||item.id||crypto.randomUUID(),type:"function" as const,function:{name:item.name!,arguments:item.arguments||"{}"},...(item.thoughtSignature?{thoughtSignature:item.thoughtSignature}:{})}));await writeAudit(db,{actor,action:"chat.completed",targetType:"model",targetId:input.modelId,result:"success",detail:{toolCallCount:toolCalls.length},ip:request.ip});response.json({content,toolCalls});}catch(error){next(error);}});return router;}
