import { Router } from "express";
import { z } from "zod";
import type { Database } from "../db";
import { requireRole } from "../rbac";
import type { AuthenticatedRequest } from "../types";

const syncSchema=z.object({externalId:z.string().min(1).max(200),name:z.string().trim().min(1).max(200)});
export function createProjectsRouter(db:Database){const router=Router();router.get("/",async(request,response,next)=>{try{const actor=(request as unknown as AuthenticatedRequest).auth;const result=await db.query(`SELECT p.id,p.external_id AS "externalId",p.name,p.status,p.created_at AS "createdAt",p.updated_at AS "updatedAt" FROM projects p LEFT JOIN project_members pm ON pm.project_id=p.id WHERE p.owner_user_id=$1 OR pm.user_id=$1 ORDER BY p.updated_at DESC`,[actor.id]);response.json({projects:result.rows});}catch(error){next(error);}});router.post("/sync",async(request,response,next)=>{try{const input=syncSchema.parse(request.body);const actor=(request as unknown as AuthenticatedRequest).auth;const result=await db.query(`INSERT INTO projects(external_id,name,owner_user_id,department_id) VALUES($1,$2,$3,$4) ON CONFLICT(external_id) DO UPDATE SET name=CASE WHEN projects.owner_user_id=EXCLUDED.owner_user_id THEN EXCLUDED.name ELSE projects.name END,updated_at=now() RETURNING id,external_id AS "externalId",name,status`,[input.externalId,input.name,actor.id,actor.departmentId]);await db.query("INSERT INTO project_members(project_id,user_id,role) VALUES($1,$2,'owner') ON CONFLICT DO NOTHING",[result.rows[0].id,actor.id]);response.json({project:result.rows[0]});}catch(error){next(error);}});router.post("/:id/members",async(request,response,next)=>{try{const actor=(request as unknown as AuthenticatedRequest).auth;const input=z.object({userId:z.string().uuid(),role:z.enum(["editor","member"]).default("member")}).parse(request.body);const owned=await db.query("SELECT id FROM projects WHERE id=$1 AND owner_user_id=$2",[request.params.id,actor.id]);if(!owned.rows[0]){response.status(403).json({error:"FORBIDDEN",message:"只有项目所有者可以添加成员"});return;}await db.query("INSERT INTO project_members(project_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(project_id,user_id) DO UPDATE SET role=EXCLUDED.role",[request.params.id,input.userId,input.role]);response.status(204).end();}catch(error){next(error);}});return router;}

export function createAdminProjectsRouter(db:Database){const router=Router();router.use(requireRole("super_admin","department_admin"));router.get("/",async(request,response,next)=>{try{const actor=(request as unknown as AuthenticatedRequest).auth;const values:unknown[]=[];const where=actor.role==="department_admin"?(values.push(actor.departmentId),"WHERE p.department_id=$1"):"";const result=await db.query(`SELECT p.id,p.external_id AS "externalId",p.name,u.display_name AS "ownerName",d.name AS "departmentName",p.status,
        (SELECT COUNT(*)::int FROM tasks t WHERE t.project_id=p.external_id) AS "taskCount",
        (SELECT COUNT(*)::int FROM assets a WHERE a.project_external_id=p.external_id AND a.deleted_at IS NULL) AS "assetCount",
        (SELECT COALESCE(SUM(h.credits),0)::int FROM generation_history h WHERE h.project_id=p.external_id) AS credits,p.updated_at AS "updatedAt"
        FROM projects p JOIN users u ON u.id=p.owner_user_id LEFT JOIN departments d ON d.id=p.department_id ${where} ORDER BY p.updated_at DESC`,values);response.json({projects:result.rows});}catch(error){next(error);}});return router;}
